version: '3'

services:
    # APP
    beautyflow_app:
        container_name: beautyflow_app
        build:
            context: .
            dockerfile: .docker/local/Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-9000}:9000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - '.docker/local/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - beautyflow_bridge
        depends_on:
            - beautyflow_pgsql
            - beautyflow_redis
    # NGINX
    beautyflow_nginx:
        container_name: beautyflow_nginx
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8888:80"
        volumes:
            - '.:/var/www/html'
            - '.docker/local/nginx/site.conf:/etc/nginx/conf.d/default.conf'
            - '.docker/local/nginx/logs/:/var/log/nginx/'
        networks:
            - beautyflow_bridge
        depends_on:
            - beautyflow_app

    # PGSQL
    beautyflow_pgsql:
        container_name: beautyflow_pgsql
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'beautyflow-pgsql:/var/lib/postgresql/data'
        networks:
            - beautyflow_bridge
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s

    # REDIS
    beautyflow_redis:
        container_name: beautyflow_redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'beautyflow-redis:/data'
        networks:
            - beautyflow_bridge
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

networks:
    beautyflow_bridge:
        driver: bridge

volumes:
    beautyflow-pgsql:
        driver: local
    beautyflow-redis:
        driver: local
